### PR TITLE
Added Earth to the scene.

### PR DESCRIPTION
**Pull request by ScepticInt**
Position of ISS is calculated by fetching ISS Trajectory data from NASA. the globe is rotated 60 degrees around the longitude so Earth, ISS and the viewer forms a like-sided triangle.
Earth is not to scale. 
Added the following node.js packets:
cheerio
request

using sattelite.min.js from https://github.com/shashwatak/satellite-js for ISS projection calculation.

### CODE REVIEW

**Comment by noopkat** [comment]
hi @c0ax!

I am very excited to see this pull request! Thanks so much for the hard work to make this site look super cool. The globe idea is amazing.

So I had an aggressive .gitignore entry which ignored any javascript files in the public/js dir. This meant that your satellite and globe files didn't make it into the commit (not your fault). Would you mind please pulling down my fix in this branch for the .gitignore and try recommitting those javascript files? Sorry about this 😅 

Then I can play with this locally before deploying to the site 🎉

**Comment by shmuelie** [comment]
@ScepticInt where did you get the `world-50m.json` file from?

**Comment by ScepticInt** [comment]
I forgot to push the Credits file. 
The map json is from d3js.org/d/5685937/

**Comment by shmuelie** [comment]
@ScepticInt that 404s

**Comment by ScepticInt** [comment]
Must have been moved, Found it here though:
https://github.com/d3/d3-geo/tree/master/test/data/

**Comment by shmuelie** [comment]
Perfect, that answered my question of what format the file was in.

The file is in [RFC-7946](https://tools.ietf.org/html/rfc7946) and EXTREMELY detailed. Way more detailed than needed. We need to find a less detailed version. Not sure from where off the top my head.

**Comment by ScepticInt** [comment]
@SamuelEnglard i'm making quite a lot of changes, There were a lot of really good comments in Noopkat's twitch, the plan now is to move the calculations to Azure and there generate a 2D projection from the globe. I'm making a new map file as well, it will be greatly reduced. my repo is here https://github.com/ScepticInt/step-to-space , on the branch globeview. you are welcome to push request any improvements :)

**Comment by ScepticInt** [comment]
@noopkat  I'm closing this PR since there is another solution being worked on.  Many thanks for great feedback :)

**Pull request closed without merging**
